name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # - name: Cache cargo binaries
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       ~/.cargo/bin
      #     key: ${{ runner.os }}-cargo-binaries

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - run: cargo install wasm-pack
      - run: cargo update --verbose
      - run: cargo build --verbose
      - run: wasm-pack build

      - run: npm install
        working-directory: www

      - run: npm run build
        working-directory: www
      
      - name: Publish
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./www/dist
          deploy_key: ${{ secrets.PAGES_DEPLOY_KEY }}
          force_orphan: true